language: node_js
node_js:
  - "8"

sudo: required

branches:
  only:
    - master

addons:
  apt:
    packages:
      - bash

services:
  - docker

jobs:
  include:
    - stage: test
      install:
        - npm install
      script:
        - npm run test

    - stage: deploy
      before_install:
        - sudo chmod +x build_docker_image.sh
        - sudo chmod +x push_docker_image.sh
      before_script:
        - ./build_docker_image.sh
      script:
        - ./push_docker_image.sh

stages:
  - test
  - name: deploy
    if: type = push

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ifaisalalam@gmail.com
