language: node_js
node_js:
  - "10"

sudo: required

branches:
  only:
    - master

addons:
  apt:
    packages:
      - bash

services:
  - docker

jobs:
  include:
    - stage: test
      before_install:
        - sudo chmod +x pull_worker_images.sh
        - sudo chmod +x build_docker_image.sh
        - sudo chmod +x test_as_docker.sh
      install:
        - npm install
        - ./build_docker_image.sh
      before_script:
        - ./pull_worker_images.sh
      script:
        - npm run test
        - ./test_as_docker.sh

    - stage: deploy
      before_install:
        - sudo chmod +x build_docker_image.sh
        - sudo chmod +x push_docker_image.sh
      install:
        - ./build_docker_image.sh
      script:
        - ./push_docker_image.sh

stages:
  - test
  - name: deploy
    if: type = push

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ifaisalalam@gmail.com
